//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finaliza la ejecución del método {0}. Fecha Fin: {1} {2}.
        /// </summary>
        internal static string GestorCalculosDebug_RegistroFinMetodo {
            get {
                return ResourceManager.GetString("GestorCalculosDebug_RegistroFinMetodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia la ejecución del método {0}. Fecha Inicio: {1} {2}.
        /// </summary>
        internal static string GestorCalculosDebug_RegistroInicioMetodo {
            get {
                return ResourceManager.GetString("GestorCalculosDebug_RegistroInicioMetodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el valor de la clave {0} en la lista de valores iniciales. Nombre de la columna en archivo de configuración: {1}, Campo en la base de datos: {2}.
        /// </summary>
        internal static string GestorCalculosError_BusquedaClaveValor {
            get {
                return ResourceManager.GetString("GestorCalculosError_BusquedaClaveValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un problema en la ejecución del cálculo con el identificador {0}. El detalle del error es el siguiente: {1}.
        /// </summary>
        internal static string GestorCalculosError_Calculo {
            get {
                return ResourceManager.GetString("GestorCalculosError_Calculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cálculo con identificador {0} que intenta ejecutar, no existe en la configuración.
        /// </summary>
        internal static string GestorCalculosError_CalculoAEjecutar {
            get {
                return ResourceManager.GetString("GestorCalculosError_CalculoAEjecutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cálculo con identificador {0}, no pertence al grupo {1} que intenta ejecutar.
        /// </summary>
        internal static string GestorCalculosError_CalculoNoPerteneceGrupo {
            get {
                return ResourceManager.GetString("GestorCalculosError_CalculoNoPerteneceGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string GestorCalculosError_CodigoGenerico {
            get {
                return ResourceManager.GetString("GestorCalculosError_CodigoGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un error en el procesamiento del archivo de configuración.
        /// </summary>
        internal static string GestorCalculosError_Configuracion {
            get {
                return ResourceManager.GetString("GestorCalculosError_Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La configuración especificada no existe.
        /// </summary>
        internal static string GestorCalculosError_ConfiguracionInexistente {
            get {
                return ResourceManager.GetString("GestorCalculosError_ConfiguracionInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un problema obteniendo el valor constante {0} desde el indice especificado de los parámetros, o la expresión para obtener los parámetros no esta bien formada. Favor verificar el archivo de configuración.
        /// </summary>
        internal static string GestorCalculosError_ConstanteParametro {
            get {
                return ResourceManager.GetString("GestorCalculosError_ConstanteParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un problema obteniendo el valor constante desde la expresión de subcadena especificada. Favor verificar el archivo de configuración.
        /// </summary>
        internal static string GestorCalculosError_ConstanteSubcadena {
            get {
                return ResourceManager.GetString("GestorCalculosError_ConstanteSubcadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cálculo {0} tiene definida una dependencia al cálculo {1} que no existe. El cálculo {0} no se ejecuta.
        /// </summary>
        internal static string GestorCalculosError_DependenciaCalculo {
            get {
                return ResourceManager.GetString("GestorCalculosError_DependenciaCalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cálculo {0} tiene definida una dependencia al cálculo {1}, y este no ha sido completado exitosamente. El cálculo {0} no se ejecuta.
        /// </summary>
        internal static string GestorCalculosError_DependenciaCalculoNoExitosa {
            get {
                return ResourceManager.GetString("GestorCalculosError_DependenciaCalculoNoExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El grupo {1} del cual depende el cálculo {0}, no existe.
        /// </summary>
        internal static string GestorCalculosError_DependenciaGropoNoExiste {
            get {
                return ResourceManager.GetString("GestorCalculosError_DependenciaGropoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cálculo {0} tiene una dependencia al grupo {1}, el cual contiene el cálculo {2} que no ha sido completado exitosamente. El cálculo {0} no se ejecuta.
        /// </summary>
        internal static string GestorCalculosError_DependenciaGrupoNoExitosa {
            get {
                return ResourceManager.GetString("GestorCalculosError_DependenciaGrupoNoExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle técnico del error: {0}.
        /// </summary>
        internal static string GestorCalculosError_DetalleTecnicoError {
            get {
                return ResourceManager.GetString("GestorCalculosError_DetalleTecnicoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problema presentado en la fuente de información {0}.
        /// </summary>
        internal static string GestorCalculosError_ExcepcionEnFuente {
            get {
                return ResourceManager.GetString("GestorCalculosError_ExcepcionEnFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó una excepción no controlada en la ejecución del método {0}.
        /// </summary>
        internal static string GestorCalculosError_ExcepcionNoControlada {
            get {
                return ResourceManager.GetString("GestorCalculosError_ExcepcionNoControlada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó la siguiente excepción en el proceso de cálculo: {0}. Para mayor detalle, favor verificar el archivo de Log del servicio.
        /// </summary>
        internal static string GestorCalculosError_ExcepcionProceso {
            get {
                return ResourceManager.GetString("GestorCalculosError_ExcepcionProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El grupo con identificador {0} que intenta ejecutar, no existe en la configuración.
        /// </summary>
        internal static string GestorCalculosError_GrupoAEjecutar {
            get {
                return ResourceManager.GetString("GestorCalculosError_GrupoAEjecutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador {0}, ya se encuentra en el diccionario.
        /// </summary>
        internal static string GestorCalculosError_KeyRepetido {
            get {
                return ResourceManager.GetString("GestorCalculosError_KeyRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La variable {0} no se encuentra en el archivo de configuración y es obligatoria.
        /// </summary>
        internal static string GestorCalculosError_MensajeValorConfiguracion {
            get {
                return ResourceManager.GetString("GestorCalculosError_MensajeValorConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas en la ejecución del proceso de cálculo asíncrono.
        /// </summary>
        internal static string GestorCalculosError_ProcesamientoAsincrono {
            get {
                return ResourceManager.GetString("GestorCalculosError_ProcesamientoAsincrono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó un problema en el procesamiento asíncrono del cálculo. El detalle de la excepción es el siguiente: {0}.
        /// </summary>
        internal static string GestorCalculosError_ProcesamientoAsincronoCompletadoConError {
            get {
                return ResourceManager.GetString("GestorCalculosError_ProcesamientoAsincronoCompletadoConError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso de cálculo especificado no existe.
        /// </summary>
        internal static string GestorCalculosError_ProcesoNoExiste {
            get {
                return ResourceManager.GetString("GestorCalculosError_ProcesoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El repositorio {0} no es válido. Revise que las consultas o procedimientos almacenados esten correctamente definidos.
        /// </summary>
        internal static string GestorCalculosError_RepositorioInvalido {
            get {
                return ResourceManager.GetString("GestorCalculosError_RepositorioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron datos para la siguiente entrada del cálculo: {0}.
        /// </summary>
        internal static string GestorCalculosError_RepositorioSinDatos {
            get {
                return ResourceManager.GetString("GestorCalculosError_RepositorioSinDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el servicio {0} en el contenedor de instancias.
        /// </summary>
        internal static string GestorCalculosError_ServicioNoEncontrado {
            get {
                return ResourceManager.GetString("GestorCalculosError_ServicioNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo de configuración enviado no cumplió con la validación del esquema XSD.
        /// </summary>
        internal static string GestorCalculosError_ValidacionArchivo {
            get {
                return ResourceManager.GetString("GestorCalculosError_ValidacionArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [ErrorXSD] [Línea {1}, Posición {2}]: {0}.
        /// </summary>
        internal static string GestorCalculosError_ValidacionEsquema {
            get {
                return ResourceManager.GetString("GestorCalculosError_ValidacionEsquema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El repositorio con identificador {0}, no paso la validación de la consulta SQL. Favor verifique la consulta e intentelo de nuevo.
        /// </summary>
        internal static string GestorCalculosError_ValidacionInyeccionSQL {
            get {
                return ResourceManager.GetString("GestorCalculosError_ValidacionInyeccionSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se definio una fuente de información para la variable {0}.
        /// </summary>
        internal static string GestorCalculosError_VariableFuente {
            get {
                return ResourceManager.GetString("GestorCalculosError_VariableFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La variable con identificador {0} es inválida. Debe ser del tipo Decimal.
        /// </summary>
        internal static string GestorCalculosError_VariableInvalida {
            get {
                return ResourceManager.GetString("GestorCalculosError_VariableInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La variable con identificador {0} es requerida y se encuentra nula sin un valor por defecto.
        /// </summary>
        internal static string GestorCalculosError_VariableNula {
            get {
                return ResourceManager.GetString("GestorCalculosError_VariableNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se definio una fuente de información para la variable semilla {0}.
        /// </summary>
        internal static string GestorCalculosError_VariableSemillaFuente {
            get {
                return ResourceManager.GetString("GestorCalculosError_VariableSemillaFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de dato de la variable semilla {0}, es inválido. Recuerde que el tipo de dato de la variable semilla debe ser DictionaryString.
        /// </summary>
        internal static string GestorCalculosError_VariableSemillaInvalida {
            get {
                return ResourceManager.GetString("GestorCalculosError_VariableSemillaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finaliza el proceso &apos;{0}&apos;.
        /// </summary>
        internal static string GestorCalculosInfo_FinProceso {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_FinProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia el proceso &apos;{0}&apos;.
        /// </summary>
        internal static string GestorCalculosInfo_InicioProceso {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_InicioProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obteniendo la configuración &apos;{0}&apos;.
        /// </summary>
        internal static string GestorCalculosInfo_ObtenerConfiguracionPorNombre {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_ObtenerConfiguracionPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando el cálculo {0}....
        /// </summary>
        internal static string GestorCalculosInfo_ProcesandoCalculo {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_ProcesandoCalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso de cálculo se encuentra activo.
        /// </summary>
        internal static string GestorCalculosInfo_ProcesoActivo {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_ProcesoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso de cálculo fue cancelado por el usuario.
        /// </summary>
        internal static string GestorCalculosInfo_ProcesoCancelado {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_ProcesoCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso de cálculo fue completado.
        /// </summary>
        internal static string GestorCalculosInfo_ProcesoCompletado {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_ProcesoCompletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso de cálculo especificado ya no se encuentra disponible en la caché.
        /// </summary>
        internal static string GestorCalculosInfo_ProcesoNoDisponible {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_ProcesoNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizo el proceso para el cálculo {0}. Resultado: {1}.
        /// </summary>
        internal static string GestorCalculosInfo_ResultadoCalculo {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_ResultadoCalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El resultado de la variable {0} es: {1}.
        /// </summary>
        internal static string GestorCalculosInfo_ResultadoVariable {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_ResultadoVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ------------------------------------------------------------.
        /// </summary>
        internal static string GestorCalculosInfo_Separador {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_Separador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando la configuración &apos;{0}&apos;.
        /// </summary>
        internal static string GestorCalculosInfo_ValidarConfiguracion {
            get {
                return ResourceManager.GetString("GestorCalculosInfo_ValidarConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [WarningXSD] [Línea {1}, Posición {2}]: {0}.
        /// </summary>
        internal static string GestorCalculosWarning_ValidacionEsquema {
            get {
                return ResourceManager.GetString("GestorCalculosWarning_ValidacionEsquema", resourceCulture);
            }
        }
    }
}
